Make main sections and cards linkable
GoogleChromeLabs/fugu-tracker pull request #23
Opened 2021-05-27 10:51 UTC by tomayac

Fixes #14

- [X] Tests pass
- [X] Appropriate changes to README are included in PR

2021-05-27 10:54 UTC, tomayac commented
Linking to main section: 

<img width="701" alt="Screen Shot 2021-05-27 at 12 53 50" src="https://user-images.githubusercontent.com/145676/119814409-a84a5300-beea-11eb-892f-71a38bb357bb.png">

Linking to individual feature: 

<img width="706" alt="Screen Shot 2021-05-27 at 12 54 10" src="https://user-images.githubusercontent.com/145676/119814416-a97b8000-beea-11eb-8c53-0075c29f88ad.png">

2021-05-27 14:10 UTC, Snugug requested changes
Thanks for your work here Tom! Really appreciate you jumping in and working on this! I've got a couple of comments here. If you could take a look I'd appreciate it!

Thanks!

2021-05-27 14:10 UTC, Snugug commented on src/css/list.scss
> +  padding-block-start: 45px !important;
A couple of comments here:
* `.card:target` should go in the [cards Sass partial](https://github.com/GoogleChromeLabs/fugu-tracker/blob/main/src/css/components/_cards.scss) and the general targeting one should go in the [core](https://github.com/GoogleChromeLabs/fugu-tracker/blob/main/src/css/components/_core.scss) partial
* Can you please swap from `px` to `rem`? All of the rest of the sizing on the site is done with rems to respond to user sizing, and we'd want this to do the same.
  * To go along with that, I'm not sure padding is what we want here; that'll add an extra space in the list. I think what we want is for cards to have a negative block margin and a positive block padding of the same size to "cancel out" their position while providing the needed block spacing to accommodate the sticky header without changing the the design or total block spacing when an item is targeted.
* Finally, we should avoid the use of `!important` wherever possible; is it possible to make the desired changes work without it?

Thanks!

2021-05-27 14:10 UTC, Snugug commented on views/index.html
> +  <h2 id="{{sections[type].split(' ').slice(0, 2).join('-') | slug}}">{{sections[type] | safe}} <a href="#{{sections[type].split(' ').slice(0, 2).join('-') | slug}}">#</a></h2>
```suggestion
  {% set sectionID = "{{sections[type].split(' ').slice(0, 2).join('-') | slug}}" %}
  <h2 id="{{sectionID}}">{{sections[type] | safe}} <a href="#{{sectionID}}">#</a></h2>
```

Because it's being used in two places, we can use Nunjuck's [set](https://mozilla.github.io/nunjucks/templating.html#set) functionality to make sure we've got the same thing in both places by making an on-the-fly variable.

2021-05-27 14:10 UTC, Snugug commented on templates/includes/card.html
> +      <a href="#{{api.title | slug}}">#</a>
I think I'd prefer the alternative functionality described in the original issue where opening a card deep links to it in the URL bar because I'm concerned that adding a separate link here might make for too many "hot spots" in the card title and may confuse users as to the different functionality between tapping the title and the link. The [toggleCardDetails](https://github.com/GoogleChromeLabs/fugu-tracker/blob/main/src/js/lib/utils.ts#L20-L35) function feels like the right place to put that as it's already called in the handful of places where the card open functionality exists.

Additionally, probably again using that function, when a user navigates to a page with the active URL, I'd like to see active card open, not just highlighted.

2021-05-27 14:35 UTC, tomayac commented
@christianliebel Do you have cycles to pull this over the finish line? I have a couple of things pending still.

2021-06-01 15:55 UTC, tomayac commented
@Snugug PTAL, this now purely focuses on the main section links (Shipped, Origin Trial, Dev Trial,…).

2021-06-02 15:30 UTC, Snugug requested changes
Thanks Tom!

Just one small comment; a suggested change from the previous round of review that didn't make it in.

Thanks!

2021-06-02 15:30 UTC, Snugug commented on views/index.html
> +  <h2 id="{{sections[type].split(' ').slice(0, 2).join('-') | slug}}">{{sections[type] | safe}} <a href="#{{sections[type].split(' ').slice(0, 2).join('-') | slug}}">#</a></h2>
Hey Tom, thanks for taking this PR back down to just section links. Can you please update this line so we're not calculating the ID twice? It'll make this easier to read. Thanks!

2021-06-03 11:19 UTC, tomayac commented
Oops, thanks. I pressed the button to add it to the list, but then forgot to press the commit button. @Snugug PTAL.

2021-06-08 16:02 UTC, Snugug approved these changes

2021-06-08 16:02 UTC, merged